# the name of your main file, with no extension
TARGET = lis331hh
# the C source files
SRC =
# the C++ source files
PSRC = main.cpp
# extra Arduino libraries
ARDLIBS = Wire LIS331HH

include ../Makefile.base