# the name of your main file, with no extension
TARGET = basic_test
# the C source files
SRC =
# the C++ source files
PSRC = basic_test.cpp
# extra Arduino libraries
ARDLIBS = RFM69 Servo Wire MPL3115A2 SPI LIS311HH

include ../Makefile.base
