# the name of your main file, with no extension
TARGET = sensor_test
# the C source files
SRC =
# the C++ source files
PSRC = sensor_test.cpp
# extra Arduino libraries
ARDLIBS =

include ../Makefile.base
