# the name of your main file, with no extension
TARGET = rover_ESC_test
# the C source files
SRC =
# the C++ source files
PSRC = rover_ESC_test.cpp
# extra Arduino libraries
ARDLIBS = Servo
ARDCORELIBS = WInterrupts WMath hooks wiring wiring_digital wiring_analog HardwareSerial HardwareSerial0 Print Stream WString abi
MCU = atmega644p
AVRDUDE_MCU = m644p
AVRDUDE_PORT = COM3 //change

include ../Makefile.base
