# the name of your main file, with no extension
TARGET = ejection
# the C source files
SRC =
# the C++ source files
PSRC = main.cpp
# extra Arduino libraries
ARDLIBS = RFM69 Servo Wire MPL3115A2 SPI

include ../Makefile.base