# the name of your main file, with no extension
TARGET = ejection
# the C source files
SRC =
# the C++ source files
PSRC = ejection.cpp
# extra Arduino libraries
ARDLIBS = RFM69 Servo Wire MPL3115A2 SPI LIS331HH
ARDCORELIBS = WInterrupts hooks wiring wiring_digital HardwareSerial HardwareSerial0 Print Stream WMath WString abi

include ../Makefile.base
