# the name of your main file, with no extension
TARGET = basic_test
# the C source files
SRC =
# the C++ source files
PSRC = basic_test.cpp
# extra Arduino libraries
ARDLIBS = SPI RFM69 Servo

include ../Makefile.base