# the name of your main file, with no extension
TARGET = sparkfun_test
# the C source files
SRC =
# the C++ source files
PSRC = sparkfun_test.cpp
# extra Arduino libraries
ARDLIBS = Wire

include ../Makefile.base