# the name of your main file, with no extension
TARGET = uart_to_radio
# the C source files
SRC =
# the C++ source files
PSRC = uart_to_radio.cpp
# extra Arduino libraries
ARDLIBS = SPI RFM69

include ../Makefile.base