# the name of your main file, with no extension
TARGET = serial_test
# the C source files
SRC =
# the C++ source files
PSRC = serial_test.cpp
# extra Arduino libraries
ARDLIBS = 

include ../../Makefile.base