#!/bin/bash

avr-gcc -g -mmcu=atmega328 -c "$1".c
avr-gcc -g -mmcu=atmega328 -o "$1".bin "$1".o
avr-objcopy -j .text -j .data -O ihex "$1".bin "$1".hex
avrdude -c avrispmkii -P /dev/tty.usbserial-A900927f -p atmega328 -U flash:w:"$1".hex
