# the name of your main file, with no extension
TARGET = deployment
# the C source files
SRC =
# the C++ source files
PSRC = deployment.cpp
# extra Arduino libraries
ARDLIBS = Wire MPL3115A2 LIS331HH

include ../Makefile.base
