# the name of your main file, with no extension
TARGET = sensors_test
# the C source files
SRC =
# the C++ source files
PSRC = sensors_test.cpp
# extra Arduino libraries
ARDLIBS = Wire MPL3115A2 LIS331HH

include ../Makefile.base
