# the name of your main file, with no extension
TARGET = basic_test
# the C source files
SRC =
# the C++ source files
PSRC = basic_test.cpp
# extra Arduino libraries
ARDLIBS = Wire MPL3115A2

include ../Makefile.base
