# the name of your main file, with no extension
TARGET = flight_computer_uart_output
# the C source files
SRC =
# the C++ source files
PSRC = flight_computer_uart_output.cpp
# extra Arduino libraries
ARDLIBS =# SPI RFM69

include ../Makefile.base