# the name of your main file, with no extension
TARGET = ground_test
# the C source files
SRC =
# the C++ source files
PSRC = ground_test.cpp
# extra Arduino libraries
ARDLIBS = SPI RFM69
ARDCORELIBS = WInterrupts hooks wiring wiring_digital HardwareSerial HardwareSerial0 Print Stream WMath WString abi

include ../Makefile.base
