# the name of your main file, with no extension
TARGET = stepper_motor
# the C source files
SRC =
# the C++ source files
PSRC = stepper_motor.cpp
# extra Arduino libraries
ARDLIBS = SPI 
ARDCORELIBS = WInterrupts hooks wiring wiring_digital HardwareSerial HardwareSerial0 Print Stream WMath WString abi

include ../Makefile.base
